version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.3 
        environment:
          NOMAD_VERSION: 0.11.2

    steps:
      - checkout
      - setup_remote_docker
                          
      - run:
          name: Build and push Docker image
          command: |
            docker build --build-arg NOMAD_VERSION=${NOMAD_VERSION}  -t cloud-registry.simulprod.com/nomad-enterprise:${NOMAD_VERSION} .
            docker push cloud-registry.simulprod.com/nomad-enterprise:${NOMAD_VERSION}

          

workflows:
  version: 2
  build:
    jobs:
      - build
